name:                 circuits-perf
version:              0.1.0.0
visibility:           public
id:                   circuits-perf-0.1.0.0-inplace
key:                  circuits-perf-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           tonyday567@gmail.com
author:               Tony Day
category:             performance
abi:                  inplace
exposed:              True
exposed-modules:      Circuit.Perf
import-dirs:
    /Users/tonyday567/haskell/circuits-perf/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-perf-0.1.0.0/build

library-dirs:
    /Users/tonyday567/haskell/circuits-perf/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-perf-0.1.0.0/build

library-dirs-static:
    /Users/tonyday567/haskell/circuits-perf/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-perf-0.1.0.0/build

dynamic-library-dirs:
    /Users/tonyday567/haskell/circuits-perf/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-perf-0.1.0.0/build

data-dir:             /Users/tonyday567/haskell/circuits-perf/.
hs-libraries:         HScircuits-perf-0.1.0.0-inplace
depends:
    base-4.22.0.0-1f90 clck-0.8.4-87884b8c deepseq-1.5.1.0-f1e0

haddock-interfaces:
    /Users/tonyday567/haskell/circuits-perf/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-perf-0.1.0.0/doc/html/circuits-perf/circuits-perf.haddock

haddock-html:
    /Users/tonyday567/haskell/circuits-perf/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-perf-0.1.0.0/doc/html/circuits-perf
